<a href="https://colab.research.google.com/github/kjh1311990/face/blob/main/dlib_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [78]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [79]:
import dlib
import matplotlib.pyplot as plt
import numpy as np

In [80]:
detector = dlib.get_frontal_face_detector()
 
sp = dlib.shape_predictor('/content/drive/MyDrive/Notebooks/shape_predictor_5_face_landmarks.dat')
facerec = dlib.face_recognition_model_v1('/content/drive/MyDrive/Notebooks/dlib_face_recognition_resnet_model_v1.dat')

In [100]:
img1_rep = np.zeros((5,128))
img2_rep = np.zeros((5,128))

Img1_rep = np.zeros((5,128))
Img2_rep = np.zeros((5,128))

for i in range(0,5):
  img1 = dlib.load_rgb_image('/content/drive/MyDrive/Notebooks/face/input/1/' + str(i) + '.jpg')
  img1_detection = detector(img1, 1)
  img1_shape = sp(img1, img1_detection[0])
  img1_aligned = dlib.get_face_chip(img1, img1_shape)
  tmp = facerec.compute_face_descriptor(img1_aligned)
  img1_rep[i] = np.array(tmp)

  img1 = dlib.load_rgb_image('/content/drive/MyDrive/Notebooks/face/input/3/' + str(i) + '.jpg')
  img1_detection = detector(img1, 1)
  img1_shape = sp(img1, img1_detection[0])
  img1_aligned = dlib.get_face_chip(img1, img1_shape)
  tmp = facerec.compute_face_descriptor(img1_aligned)
  img2_rep[i] = np.array(tmp)  

In [101]:
t1 = img1_rep.max(axis=0) - img1_rep.min(axis=0)

In [130]:
for i in range(0,5):
  for j in range(0,128):
    Img1_rep[i][j] = img1_rep[i][j] / (4 * t1[j]) 

In [131]:
for i in range(0,5):
  for j in range(0,128):
    Img2_rep[i][j] = img2_rep[i][j] / (4 * t1[j]) 

In [132]:
img1_rep[0]

array([-0.06291559,  0.05148215, -0.00347966,  0.00817019, -0.06519566,
       -0.09239063, -0.02158191, -0.12839273,  0.11782277, -0.0942307 ,
        0.18532132, -0.08314824, -0.20296691, -0.12079628, -0.04843768,
        0.16994822, -0.12343431, -0.13511431, -0.06738358,  0.01905569,
        0.1976378 ,  0.01160794, -0.01658015,  0.06463371, -0.11462639,
       -0.29766667, -0.11916296, -0.08141525,  0.03104168, -0.05255121,
       -0.02518215,  0.0343201 , -0.18216865, -0.08718809,  0.02841506,
        0.04342654, -0.00536608, -0.05616228,  0.20817786, -0.00459168,
       -0.23780635,  0.05905711,  0.01413532,  0.22668326,  0.15998876,
        0.05715635,  0.04013925, -0.16620229,  0.15039174, -0.14860564,
        0.03371716,  0.1633181 ,  0.10335921,  0.10371032, -0.00750391,
       -0.10079902,  0.0715223 ,  0.08597122, -0.16365433,  0.0358147 ,
        0.09752065, -0.1048957 , -0.01529935, -0.06324224,  0.16294204,
       -0.02801612, -0.09390202, -0.15091734,  0.12855676, -0.16

In [133]:
Img1_rep[0].astype(int)

array([ 0,  0,  0,  0, -1, -1,  0, -2,  0, -1,  3,  0, -2, -2,  0,  3, -1,
       -2,  0,  0,  2,  0,  0,  1, -2, -3, -1, -1,  0,  0,  0,  0, -2,  0,
        0,  0,  0,  0,  3,  0, -3,  0,  0,  7,  3,  0,  0, -3,  1, -1,  0,
        2,  1,  1,  0,  0,  1,  0, -4,  0,  0, -2,  0,  0,  2,  0, -1, -2,
        2, -4, -1,  1, -3, -4, -3,  0,  3,  1, -2,  1,  0,  0,  3,  2,  0,
        0, -1,  0,  3, -4,  0,  3,  0,  1,  0,  0,  0,  0,  0,  0,  1,  0,
        0,  1, -5,  1,  0,  1,  0,  0, -1,  0,  1, -2,  3,  1,  0,  1,  1,
        1,  0,  0, -2,  0,  2,  0,  0,  0])

In [134]:
Img1_rep[1].astype(int)

array([ 0,  0,  0,  0, -1, -1,  0, -2,  0, -1,  3,  0, -2, -2,  0,  3, -1,
       -2,  0,  0,  2,  0,  0,  1, -2, -3, -1, -1,  0,  0,  0,  0, -2,  0,
        0,  0,  0,  0,  3,  0, -3,  0,  0,  7,  3,  0,  0, -3,  1, -2,  0,
        2,  1,  1,  0,  0,  1,  0, -4,  0,  0, -2,  0,  0,  2,  0, -1, -1,
        2, -4, -1,  1, -3, -5, -3,  0,  4,  1, -2,  1,  0,  0,  3,  2,  0,
        0, -1,  0,  3, -4,  0,  3,  0,  1,  0,  0,  0,  0,  0,  0,  1,  0,
        0,  1, -5,  1,  0,  1,  0,  0, -1,  0,  1, -2,  3,  2,  0,  1,  1,
        1,  0,  0, -2,  0,  2,  0,  0,  0])

In [135]:
Img1_rep[0].astype(int) - Img1_rep[1].astype(int)

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,
        0,  0,  0,  0,  0,  1,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0])

In [136]:
for i in range(0,5):
  for j in range(0,5):
    print(i,j,np.sum(np.abs(Img1_rep[i].astype(int)-Img1_rep[j].astype(int))));

0 0 0
0 1 5
0 2 7
0 3 8
0 4 8
1 0 5
1 1 0
1 2 8
1 3 7
1 4 9
2 0 7
2 1 8
2 2 0
2 3 7
2 4 7
3 0 8
3 1 7
3 2 7
3 3 0
3 4 8
4 0 8
4 1 9
4 2 7
4 3 8
4 4 0


In [137]:
for i in range(0,5):
  for j in range(0,5):
    print(i,j,np.sum(np.abs(Img1_rep[i].astype(int)-Img2_rep[j].astype(int))));

0 0 51
0 1 49
0 2 52
0 3 56
0 4 46
1 0 54
1 1 52
1 2 55
1 3 55
1 4 45
2 0 52
2 1 50
2 2 53
2 3 57
2 4 47
3 0 51
3 1 49
3 2 52
3 3 54
3 4 44
4 0 55
4 1 53
4 2 56
4 3 60
4 4 50


In [110]:
Img1_rep[0].astype(int) - Img2_rep[0].astype(int)

array([ 1, -1,  0,  0,  1, -1,  0,  1,  1,  0, -1, -1,  0,  0,  0, -1,  1,
        0,  0,  0,  2,  1,  0,  1,  0,  0,  0,  0, -1,  0,  2,  0,  0,  0,
        0,  0,  1,  1,  2,  0,  0,  0,  0,  1,  0,  0,  0, -1,  0, -1,  0,
        1,  0,  1,  0,  1,  1,  0, -2, -1,  0, -1,  0,  0, -1,  0,  0,  0,
        0, -2,  0,  1,  0,  0, -1,  0,  0,  0, -1,  1,  0,  0,  2,  0,  0,
        0,  0,  0,  1, -2,  0,  1,  1,  1,  0,  0,  1, -4,  0,  0,  0,  1,
        0, -1,  1,  2,  0, -1,  0,  0,  0,  0,  1,  1, -1, -1,  0,  0, -1,
        0,  0,  0,  0,  0,  1,  0,  1, -1])

In [111]:
Img2_rep[0].astype(int)

array([-1,  1,  0,  0, -2, -1,  0, -4,  0, -1,  5,  0, -2, -3,  0,  5, -2,
       -2,  0,  0,  1, -1,  0,  0, -3, -3, -1, -1,  1,  0, -2,  0, -3,  0,
        0,  0, -1, -1,  2,  0, -3,  0,  0,  7,  3,  0,  0, -3,  1, -1,  0,
        1,  1,  0,  0, -1,  0,  0, -3,  1,  0, -1,  0,  0,  3,  0, -1, -2,
        2, -2, -1,  0, -3, -5, -3,  0,  4,  1, -2,  0,  0,  0,  2,  2,  0,
        0, -1,  0,  3, -3,  0,  2, -1,  0,  0,  0, -1,  4,  0,  0,  1, -1,
        0,  2, -7,  0,  0,  2,  0,  0, -2,  0,  1, -3,  4,  3,  0,  1,  2,
        1,  0,  0, -2,  0,  1,  0,  0,  1])

In [112]:
Img2_rep[1].astype(int)

array([ 0,  0,  0,  0, -2, -1,  0, -4,  0, -2,  5, -1, -2, -3,  0,  5, -2,
       -2,  0,  0,  0, -1,  0,  0, -2, -3, -1, -1,  0,  0, -2,  0, -3,  0,
        0,  0, -1, -1,  2,  0, -3,  0,  0,  7,  3,  0,  0, -3,  1, -1,  0,
        1,  1,  0,  0, -1,  1,  0, -3,  0,  0, -1,  0,  0,  3,  0, -1, -2,
        2, -2, -1,  0, -3, -4, -4,  0,  4,  1, -2,  0,  0,  0,  2,  2,  0,
        0, -1,  0,  3, -3, -1,  2, -1,  0,  0,  0, -1,  3,  0,  0,  1, -1,
        0,  2, -6,  0,  0,  2,  0,  0, -2, -1,  2, -3,  3,  3,  0,  1,  2,
        2,  0,  0, -2,  0,  1,  0,  1,  1])

In [93]:
Img1_rep[0].astype(int)

array([ 0,  0,  0,  0, -1, -2,  0, -3,  1, -1,  4, -1, -2, -3,  0,  4, -1,
       -2,  0,  0,  3,  0,  0,  1, -3, -3, -1, -1,  0,  0,  0,  0, -3,  0,
        0,  0,  0,  0,  4,  0, -3,  0,  0,  8,  3,  0,  0, -4,  1, -2,  0,
        2,  1,  1,  0,  0,  1,  0, -5,  0,  0, -2,  0,  0,  2,  0, -1, -2,
        2, -4, -1,  1, -3, -5, -4,  0,  4,  1, -3,  1,  0,  0,  4,  2,  0,
        0, -1,  0,  4, -5,  0,  3,  0,  1,  0,  0,  0,  0,  0,  0,  1,  0,
        0,  1, -6,  2,  0,  1,  0,  0, -2,  0,  2, -2,  3,  2,  0,  1,  1,
        1,  0,  0, -2,  0,  2,  0,  1,  0])

In [96]:
Img2_rep[1].astype(int)

array([ 0,  0,  0,  0, -1, -1,  0, -2,  0, -1,  4, -1, -2, -2,  0,  4, -1,
       -2,  0,  0,  3,  0,  0,  1, -3, -3, -1, -1,  0,  0,  0,  0, -2,  0,
        0,  0,  0,  0,  4,  0, -3,  0,  0,  8,  3,  0,  0, -4,  1, -2,  0,
        3,  1,  1,  0,  0,  1,  0, -4,  0,  0, -2,  0,  0,  2,  0, -1, -2,
        2, -4, -1,  1, -3, -5, -3,  0,  4,  1, -3,  1, -1,  0,  3,  2,  0,
        0, -1,  0,  4, -5,  0,  3,  0,  1,  0,  0,  0,  0,  0,  0,  1,  0,
        0,  1, -6,  2,  0,  2,  0,  0, -1,  0,  2, -2,  3,  2,  0,  1,  1,
        1,  0,  0, -2,  0,  2,  0,  0,  0])

In [97]:
Img2_rep[1].astype(int) - Img2_rep[1].astype(int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [98]:
img2_rep[1]

array([-0.08045411,  0.03916463,  0.02300247,  0.00812719, -0.07048094,
       -0.08218291, -0.01436749, -0.11938636,  0.09420578, -0.09716626,
        0.19378974, -0.07937725, -0.19247314, -0.11784162, -0.04604971,
        0.16508609, -0.12229471, -0.13877094, -0.06126897,  0.01901771,
        0.18812175,  0.00204719, -0.02484917,  0.05419663, -0.10546223,
       -0.2982834 , -0.11807749, -0.07980464,  0.03832312, -0.06778151,
       -0.02743273,  0.03154368, -0.16490638, -0.04914998,  0.01550255,
        0.04559701, -0.0063225 , -0.06576106,  0.20023485, -0.00746495,
       -0.23522398,  0.06672215, -0.00923789,  0.22567056,  0.16701259,
        0.05227448,  0.02771368, -0.16856331,  0.15687445, -0.16830818,
        0.02812746,  0.17450875,  0.08712696,  0.10321584, -0.0116531 ,
       -0.09064078,  0.07366025,  0.06300675, -0.16204968,  0.03070691,
        0.08171227, -0.10188289, -0.00526488, -0.088994  ,  0.17284372,
       -0.02091388, -0.11468953, -0.13409324,  0.12578076, -0.15

In [99]:
img1_rep[1]

array([-0.08045411,  0.03916463,  0.02300247,  0.00812719, -0.07048094,
       -0.08218291, -0.01436749, -0.11938636,  0.09420578, -0.09716626,
        0.19378974, -0.07937725, -0.19247314, -0.11784162, -0.04604971,
        0.16508609, -0.12229471, -0.13877094, -0.06126897,  0.01901771,
        0.18812175,  0.00204719, -0.02484917,  0.05419663, -0.10546223,
       -0.2982834 , -0.11807749, -0.07980464,  0.03832312, -0.06778151,
       -0.02743273,  0.03154368, -0.16490638, -0.04914998,  0.01550255,
        0.04559701, -0.0063225 , -0.06576106,  0.20023485, -0.00746495,
       -0.23522398,  0.06672215, -0.00923789,  0.22567056,  0.16701259,
        0.05227448,  0.02771368, -0.16856331,  0.15687445, -0.16830818,
        0.02812746,  0.17450875,  0.08712696,  0.10321584, -0.0116531 ,
       -0.09064078,  0.07366025,  0.06300675, -0.16204968,  0.03070691,
        0.08171227, -0.10188289, -0.00526488, -0.088994  ,  0.17284372,
       -0.02091388, -0.11468953, -0.13409324,  0.12578076, -0.15