<a href="https://colab.research.google.com/github/kjh1311990/face/blob/main/keras_feature_extract_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive


In [15]:
from PIL import Image
import numpy as np
import cv2, math
face_detector = cv2.CascadeClassifier('/gdrive/My Drive/Notebooks/haarcascade_frontalface_default.xml')
eye_detector = cv2.CascadeClassifier('/gdrive/My Drive/Notebooks/haarcascade_eye.xml')

#face_detector = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
#eye_detector = cv2.CascadeClassifier('haarcascade_eye.xml')

def euclidean_distance(a, b):
    x1 = a[0]; y1 = a[1]
    x2 = b[0]; y2 = b[1]
    
    return math.sqrt(((x2 - x1) * (x2 - x1)) + ((y2 - y1) * (y2 - y1)))

In [16]:
from keras.models import load_model
from keras.models import Model

# 모델 로딩
model = load_model('/gdrive/My Drive/Notebooks/weights.h5')

In [17]:
model2 = Model(model.input, model.layers[-2].output)

In [20]:
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.applications import resnet50

img1 = load_img('/gdrive/My Drive/Notebooks/face/face1.jpg', target_size=(224,224))
img1 = img_to_array(img1)
img1 = img1.reshape((1, 224, 224, 3))
img1 = resnet50.preprocess_input(img1)

img2 = load_img('/gdrive/My Drive/Notebooks/face/face2.jpg', target_size=(224,224))
img2 = img_to_array(img2)
img2 = img2.reshape((1, 224, 224, 3))
img2 = resnet50.preprocess_input(img2)

In [21]:
 y1 = model2.predict(img1)
 y2 = model2.predict(img2)

In [22]:
y1.astype(int)

array([[ 1,  0,  0,  0,  0,  3,  6,  0,  0,  0,  0,  2,  1,  0,  0,  5,
         5,  0,  0,  0,  4,  0,  1,  2,  6,  0,  0,  0,  0,  1,  7,  0,
         2,  1,  0,  0,  3,  0,  1,  0,  5,  1,  1,  1,  0,  0,  0,  1,
         3,  0,  1,  2,  0,  0,  4,  1,  0,  0,  0,  0,  2,  0,  0,  0,
         0,  0,  0,  4,  5,  1,  0,  1,  2,  0,  2,  0,  0,  5,  0,  1,
         7,  0,  5,  7,  4,  3,  0,  5,  0,  0,  3,  0,  0,  1,  2,  0,
         0,  0,  0,  2,  0,  0,  1,  0,  0,  0,  1,  0,  0,  0,  4,  0,
         0,  1,  6,  0,  1,  1,  2,  2,  2,  6,  0,  1,  5,  0,  4,  3,
         0,  8,  0, 10,  9,  4,  2,  6,  1,  0,  0,  0,  2,  1,  2,  0,
         2,  0,  5,  0,  0,  3,  0,  4,  0,  0,  0,  0,  0,  5, 12,  0,
         0,  0,  1,  3,  0,  0,  2,  0,  5,  3,  0,  4,  0,  2,  3,  6,
         0,  4,  4,  0,  0,  5,  2,  0,  4,  0,  3,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  4,  7,  0,  0,  0,  4,  0,  3,  3,  4,  3,  0,
         0,  0,  4,  3,  0,  0,  0,  0,  4,  0,  0,  0,  3,  3, 

In [23]:
y2.astype(int)

array([[ 1,  0,  0,  2,  0,  5,  3,  0,  0,  0,  0,  3,  1,  1,  4,  7,
         7,  0,  1,  0,  2,  0,  2,  0,  9,  2,  0,  0,  0,  0,  8,  0,
         4,  1,  0,  3,  2,  0,  3,  0,  9,  0,  5,  2,  0,  0,  0,  3,
         5,  1,  2,  1,  0,  1,  1,  3,  0,  0,  0,  4,  2,  0,  3,  1,
         0,  0,  0,  6,  6,  4,  1,  2,  4,  1,  2,  3,  0,  3,  0,  0,
         5,  0,  7,  8,  2,  5,  1,  6,  0,  2,  5,  0,  0,  0,  3,  0,
         0,  0,  0,  3,  2,  0,  0,  0,  5,  0,  2,  0,  0,  0,  3,  0,
         0,  0,  4,  0,  0,  2,  1,  0,  0,  4,  0,  1,  4,  0,  0,  5,
         0,  4,  0,  6,  9,  3,  0,  2,  0,  0,  0,  0,  0,  0,  4,  0,
         4,  0,  0,  0,  0,  5,  0,  2,  0,  0,  0,  0,  0,  2, 10,  2,
         1,  0,  0,  4,  3,  0,  0,  1,  4,  4,  2,  2,  0,  2,  1,  6,
         0,  5,  4,  0,  0,  5,  3,  0,  1,  0,  6,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  4,  0,  0,  0,  0,  0,  5,  3,  0,  1,  0,
         0,  0,  2,  1,  0,  5,  0,  0,  2,  0,  0,  1,  5,  3, 

In [24]:
import numpy

numpy.linalg.norm(y1-y2)

37.644283

In [25]:
y1.astype(int)-y2.astype(int)

array([[ 0,  0,  0, -2,  0, -2,  3,  0,  0,  0,  0, -1,  0, -1, -4, -2,
        -2,  0, -1,  0,  2,  0, -1,  2, -3, -2,  0,  0,  0,  1, -1,  0,
        -2,  0,  0, -3,  1,  0, -2,  0, -4,  1, -4, -1,  0,  0,  0, -2,
        -2, -1, -1,  1,  0, -1,  3, -2,  0,  0,  0, -4,  0,  0, -3, -1,
         0,  0,  0, -2, -1, -3, -1, -1, -2, -1,  0, -3,  0,  2,  0,  1,
         2,  0, -2, -1,  2, -2, -1, -1,  0, -2, -2,  0,  0,  1, -1,  0,
         0,  0,  0, -1, -2,  0,  1,  0, -5,  0, -1,  0,  0,  0,  1,  0,
         0,  1,  2,  0,  1, -1,  1,  2,  2,  2,  0,  0,  1,  0,  4, -2,
         0,  4,  0,  4,  0,  1,  2,  4,  1,  0,  0,  0,  2,  1, -2,  0,
        -2,  0,  5,  0,  0, -2,  0,  2,  0,  0,  0,  0,  0,  3,  2, -2,
        -1,  0,  1, -1, -3,  0,  2, -1,  1, -1, -2,  2,  0,  0,  2,  0,
         0, -1,  0,  0,  0,  0, -1,  0,  3,  0, -3,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  4,  3,  0,  0,  0,  4,  0, -2,  0,  4,  2,  0,
         0,  0,  2,  2,  0, -5,  0,  0,  2,  0,  0, -1, -2,  0, 